application:
  title: FPT International Student Exchange
  currency:
    vnd:
      format: "%n %u"
      unit: VNĐ
      precision: 0
model:
  user:
    max_name_length: 30
    min_name_length: 3
    start_dob_year: 1950
  event:
    sorted_by:
      latest: latest
      most_popular: most_popular
      enrolling_phase: enrolling_phase
    per_page: 5
    max_title_length: 35
    date_format: "%d/%m/%y"
assets:
  images:
    fpt_logo: fpt_logo.png
date:
  formats:
    long: "%e, %B %Y"
